/**
 * Sources:
 * https://www.sandiego.gov/city-clerk/elections/city/2022elections
 * https://www.sandiego.gov/sites/default/files/qualified_candidates_list_2022_updated_3-29-2022.pdf
 * https://www.sandiego.gov/sites/default/files/qualified_candidates_list_november_2020_3.pdf
 * https://www.sandiego.gov/sites/default/files/qualified_candidates_list_2020_1.pdf
 * https://www.sandiego.gov/sites/default/files/qualifiedcandidates_june2018_0.pdf
 * https://www.sandiego.gov/sites/default/files/potentialcandidates2018.pdf
 *
 * https://www.sandiego.gov/city-clerk/elections/city/past/races
 */

export interface CandidateInfo {
  year: string;
  candidateId: string;
  optionalName: string;
  inPrimary: boolean;
  description: string;
  imageFileName: string;
  website: string;

  /**
   * committeeNameOverride is used to correct committee names from efile that do not match names in the xlxs files.
   * In most cases the committee name contains the candidate's first name twice.
   * example:
   *  incorrect committee name: 'First First Last for City Council 2020'
   *  committeeNameOverride: 'First Last for City Council 2020'
   */
  committeeNameOverride?: string;
}

/* Template
{
	year: '2018',
	candidateId: '',
	optionalName: '',
	inPrimary: true,
	description: '',
	imageFileName: null,
	website: '',
},
*/

export const CandidateElectionInfo: CandidateInfo[] = [
  {
    year: '2022',
    candidateId: 'd3d1c6e7-0add-49f1-9b3d-e9289e7efcf6|2022',
    optionalName: 'Campbell, Jennifer',
    inPrimary: true,
    description: 'San Diego City Councilmember/Family Physician',
    imageFileName: 'jennifer_campbell_2129.png',
    website: 'https://www.drjencampbell.com/',
  },
  {
    year: '2022',
    candidateId: '5a936cfe-bf79-02c5-f9c0-8dbc455d0a01|2022',
    optionalName: 'Day, Joel',
    inPrimary: true,
    description: 'Public Policy Educator',
    imageFileName: 'joel_day_9315.png',
    website: 'https://www.joeldaysd.com/',
  },
  {
    year: '2022',
    candidateId: 'abcbef93-0b11-4e35-99c2-09a5e5ad7771|2022',
    optionalName: 'Havlik, Mandy',
    inPrimary: true,
    description: 'Community Volunteer',
    imageFileName: 'mandy_havlik_3216.png',
    website: 'https://mandyhavlik.com/',
    committeeNameOverride: 'Mandy Havlik for City Council District 2 2022',
  },
  {
    year: '2022',
    candidateId: '12bec5c1-9fe5-4d30-9621-9039258ded42|2022',
    optionalName: 'Lukacs, Linda',
    inPrimary: true,
    description: 'Dentist/Professor',
    imageFileName: 'linda_lukacs_2795.png',
    website: 'https://www.lindalukacs.com/',
  },
  {
    year: '2022',
    candidateId: 'b3743dcf-ba16-1389-aa07-d28f26d4a94d|2022',
    optionalName: 'Saldaña, Lori',
    inPrimary: true,
    description: 'Retired Business Technology Professor',
    imageFileName: 'lori_saldana_4515.png',
    website: null,
    committeeNameOverride: 'Lori Saldana for City Council 2022',
  },
  {
    year: '2022',
    candidateId: null,
    optionalName: 'Smiechowski, Daniel',
    inPrimary: true,
    description: 'Landlord/Real Estate Sales',
    imageFileName: 'daniel_smiechowski_3042.png',
    website: null,
  },
  {
    year: '2022',
    candidateId: null,
    optionalName: 'Evangelista, Gloria',
    inPrimary: true,
    description: 'Dietitian',
    imageFileName: null,
    website: null,
  },
  {
    year: '2022',
    candidateId: '82cae978-49df-4a77-8793-0efffb7772b5|2022',
    optionalName: 'Montgomery Steppe, Monica',
    inPrimary: true,
    description: 'Councilmember',
    imageFileName: 'monica_montgomery_steppe_7929.png',
    website: 'https://www.monica4sandiego.com/',
  },
  {
    year: '2022',
    candidateId: null,
    optionalName: 'Suseberry, Tylisa D.',
    inPrimary: true,
    description: 'N/A',
    imageFileName: 'tylisa_suseberry_9754.png',
    website: null,
  },
  {
    year: '2022',
    candidateId: null,
    optionalName: 'Glasson, Jane L.',
    inPrimary: true,
    description: 'Special Education Assistant',
    imageFileName: 'jane_glasson_7726.png',
    website: 'https://www.instagram.com/jane_glasson/',
  },
  {
    year: '2022',
    candidateId: 'ea70d40e-2106-2ed2-e82c-bd320c909e9c|2022',
    optionalName: 'Hough, Tommy',
    inPrimary: true,
    description: 'County Planning Commissioner',
    imageFileName: 'tommy_hough_6050.png',
    website: null,
  },
  {
    year: '2022',
    candidateId: 'fe7d8f9d-9a13-4942-ba28-e8d690ae9136|2022',
    optionalName: 'Lee, Kent',
    inPrimary: true,
    description: 'Nonprofit Executive Director',
    imageFileName: 'kent_lee_8092.png',
    website: 'https://www.kentleeforsd.com/',
  },
  {
    year: '2022',
    candidateId: '47f2d909-5f52-d85c-b465-3ad7714b1da5|2022',
    optionalName: 'Martinez, Antonio',
    inPrimary: true,
    description: 'Congressional Community Representative',
    imageFileName: 'antonio_martinez_5314.png',
    website: 'https://www.antoniomartinezsd.com/',
    committeeNameOverride: 'Antonio Martinez for City Council 2022',
  },
  {
    year: '2022',
    candidateId: '4adb5c04-3d8d-4fdd-9cd4-1227cbde766e|2022',
    optionalName: 'Moreno, Vivian',
    inPrimary: true,
    description: 'Councilmember',
    imageFileName: 'vivian_moreno_5899.png',
    website: 'https://vivianmorenosd.com/',
  },
  {
    year: '2022',
    candidateId: '1c489060-d460-4952-b7c2-0efbb3922a78|2022',
    optionalName: 'Christina Nichols',
    inPrimary: false,
    description: '',
    imageFileName: '',
    website: null,
  },
  {
    year: '2022',
    candidateId: 'a81b1432-e927-4695-b0f9-761814fd6d3d|2022',
    optionalName: 'Nicole Crosby',
    inPrimary: false,
    description: '',
    imageFileName: '',
    website: null,
  },

  {
    year: '2020',
    candidateId: null,
    optionalName: 'Appelbaum Singh, Gita',
    inPrimary: true,
    description: 'Family Nurse Practitioner',
    imageFileName: null,
    website: null,
  },
  {
    year: '2020',
    candidateId: 'be0a57fb-c0f0-bbd5-0d42-44a6560cbd21|2020',
    optionalName: 'Bry, Barbara',
    inPrimary: true,
    description: 'Councilmember/Businesswoman',
    imageFileName: 'barbara_bry_3523.png',
    website: 'https://barbarabry.com/',
  },
  {
    year: '2020',
    candidateId: '24738d25-2b55-4ef8-b78e-dcc4442a6327|2020',
    optionalName: 'Gloria, Todd',
    inPrimary: true,
    description: 'Assemblymember',
    imageFileName: 'todd_gloria_8906.png',
    website: 'https://toddgloria.com/',
  },
  {
    year: '2020',
    candidateId: '66b8c132-1328-53b8-0623-13aed0ac4cf1|2020',
    optionalName: 'Riel, Rich',
    inPrimary: true,
    description: 'Computer Tech',
    imageFileName: null,
    website: 'https://richriel.com/',
  },
  {
    year: '2020',
    candidateId: 'f311f300-4421-5320-a6b7-a2641a33c6ce|2020',
    optionalName: 'Sherman, Scott',
    inPrimary: true,
    description: 'City Councilman',
    imageFileName: null,
    website: 'https://www.sherman2020.com/',
  },
  {
    year: '2020',
    candidateId: 'a88a9257-7390-28da-a452-060785715c85|2020',
    optionalName: 'Williamson, Tasha',
    inPrimary: true,
    description: 'Nonprofit Executive',
    imageFileName: 'tasha_williamson_3154.png',
    website: 'https://www.tasha4mayor.com/',
  },
  {
    year: '2020',
    candidateId: 'dec04882-0666-200b-4bc8-1f66a5a73471|2020',
    optionalName: 'Briggs, Cory',
    inPrimary: true,
    description: 'Attorney/Taxpayer Advocate',
    imageFileName: null,
    website: 'https://corybriggs.com/',
  },
  {
    year: '2020',
    candidateId: 'f7957bf1-8701-4456-93dc-6c7022c86b6d|2020',
    optionalName: 'Elliott, Mara W.',
    inPrimary: true,
    description: 'San Diego City Attorney',
    imageFileName: null,
    website: 'https://maraelliott.com/',
  },
  {
    year: '2020',
    candidateId: null,
    optionalName: 'Mesich, Pete',
    inPrimary: true,
    description: 'Attorney',
    imageFileName: null,
    website: 'http://petemesichforcityattorney.com/',
  },
  {
    year: '2020',
    candidateId: '38f64952-4a97-6f19-2133-ce9b7c36495c|2020',
    optionalName: 'Brennan, Aaron',
    inPrimary: true,
    description: 'Firefighter/ Naval Reserve Officer',
    imageFileName: null,
    website: 'https://aaronforsandiego.com/',
  },
  {
    year: '2020',
    candidateId: 'f9b24bfd-0c16-4d53-9f3b-0c6439f75ee4|2020',
    optionalName: 'LaCava, Joe',
    inPrimary: true,
    description: 'Civil Engineer/Business Owner',
    imageFileName: 'joe_lacava_6571.png',
    website: 'https://www.joelacava.com/',
  },
  {
    year: '2020',
    candidateId: '4786874c-3555-2a43-d582-eff1fb81be5b|2020',
    optionalName: 'Moore, Will',
    inPrimary: true,
    description: ' Small Business Counsel',
    imageFileName: null,
    website: 'http://mooreforsandiego.com/',
  },
  {
    year: '2020',
    candidateId: '08620a66-bcdf-718e-201f-16f197f3b5aa|2020',
    optionalName: 'Nejabat, Sam',
    inPrimary: true,
    description: 'Small Business Owner',
    imageFileName: null,
    website: null,
  },
  {
    year: '2020',
    candidateId: '69b885e6-49f6-3d44-88a9-5e7695ee46b8|2020',
    optionalName: 'Puentes, Harid “H.”',
    inPrimary: true,
    description: 'Tech Executive',
    imageFileName: null,
    website: 'https://www.hpuentes.com/',
  },
  {
    year: '2020',
    candidateId: null,
    optionalName: 'Rodolico, Louis A',
    inPrimary: true,
    description: 'Environmental Journalist',
    imageFileName: null,
    website: 'http://www.louisrodolico.com/',
  },
  {
    year: '2020',
    candidateId: '14836ea4-a228-5b01-7b8b-ddc63dca6f83|2020',
    optionalName: 'Rudolph, James P.',
    inPrimary: true,
    description: 'Business Attorney/Father',
    imageFileName: null,
    website: null,
  },
  {
    year: '2020',
    candidateId: '70975077-e4e8-cf7c-b5b1-31ca811f0bfb|2020',
    optionalName: 'Zhou, Lijun (Lily)',
    inPrimary: true,
    description: 'Entrepreneur/Instructor',
    imageFileName: null,
    website: 'https://www.lilyzhoucitycouncil.com/',
  },
  {
    year: '2020',
    candidateId: 'd008892d-705f-7bfe-836e-10e0707c1b5a|2020',
    optionalName: 'Duran, Toni',
    inPrimary: true,
    description: 'State Senator’s District Representative',
    imageFileName: null,
    website: 'http://www.toniforsandiego.com/',
  },
  {
    year: '2020',
    candidateId: 'adeffeff-b9bc-45af-4df2-218db023f1c3|2020',
    optionalName: 'Kwiatkowski, Adrian',
    inPrimary: true,
    description: 'CEO Non-Profit Management/Strategist',
    imageFileName: null,
    website: 'https://adrianforcitycouncil.com/',
  },
  {
    year: '2020',
    candidateId: '6b556246-fcff-ccf2-5f93-edbe77f07716|2020',
    optionalName: 'Nguyen, Michelle',
    inPrimary: true,
    description: 'Procurement Specialist/Military Reservist',
    imageFileName: null,
    website: null,
  },
  {
    year: '2020',
    candidateId: 'eab5c0ea-1707-ab0f-3d3f-f9626058ff69|2020',
    optionalName: 'Olsen, Chris',
    inPrimary: true,
    description: 'City Budget Analyst/Educator',
    imageFileName: null,
    website: 'https://votechrisolsen.com/',
  },
  {
    year: '2020',
    candidateId: 'be577485-059c-44c0-94ed-a1678106f3f0|2020',
    optionalName: 'Whitburn, Stephen',
    inPrimary: true,
    description: 'Community Nonprofit Director',
    imageFileName: 'stephen_whitburn_5861.png',
    website: 'http://whitburnforcouncil.com/',
  },
  {
    year: '2020',
    candidateId: '57a4d86c-f92a-f055-c919-7595c4300458|2020',
    optionalName: 'Leventhal, Joe',
    inPrimary: true,
    description: 'Attorney/Small Business Owner',
    imageFileName: null,
    website: 'https://joeforsandiego.com/',
  },
  {
    year: '2020',
    candidateId: null,
    optionalName: 'Moghadam, Simon',
    inPrimary: true,
    description: 'Independent Business Owner',
    imageFileName: null,
    website: 'http://www.simonmoghadam.com/',
  },
  {
    year: '2020',
    candidateId: '00e28002-c35b-4775-a1b4-8bcae533f6c0|2020',
    optionalName: 'von Wilpert, Marni',
    inPrimary: true,
    description: 'Deputy City Attorney',
    imageFileName: 'marni_von_wilpert_1942.png',
    website: 'https://www.marniforsandiego.com/',
  },
  {
    year: '2020',
    candidateId: 'cd273372-11a7-92ba-ee82-e8e780cb0e54|2020',
    optionalName: 'Wang, Isaac',
    inPrimary: true,
    description: 'Technology Entrepreneur/ Naval Reservist',
    imageFileName: null,
    website: 'https://www.isaac.vote/',
  },
  {
    year: '2020',
    candidateId: '3a37df55-6db8-463c-a874-d9d858898cb5|2020',
    optionalName: 'Campillo, Raul',
    inPrimary: true,
    description: 'Deputy City Attorney',
    imageFileName: 'raul_campillo_2263.png',
    website: 'https://runwithraul.com/',
  },
  {
    year: '2020',
    candidateId: '395b1780-367d-5d7f-e03e-7fcc285e2cf5|2020',
    optionalName: 'McIntyre, Monty',
    inPrimary: true,
    description: 'Mediator/Arbitrator/Business Owner',
    imageFileName: null,
    website: 'https://votemonty2020.com/',
  },
  {
    year: '2020',
    candidateId: '857d36df-b8c8-cf1b-3b94-3db91c2f958e|2020',
    optionalName: 'Wheatcroft, Wendy',
    inPrimary: true,
    description: 'Teacher',
    imageFileName: null,
    website: 'https://www.wendy4sd.com/',
  },
  {
    year: '2020',
    candidateId: 'e225c92e-c99b-bae4-1169-3305ebaad363|2020',
    optionalName: 'Zosa, Noli',
    inPrimary: true,
    description: 'Small Business Owner',
    imageFileName: null,
    website: 'https://www.noli2020.com/',
  },
  {
    year: '2020',
    candidateId: 'e0a65f4c-6b7d-0332-39c6-14cb3ec58699|2020',
    optionalName: 'Barrios, Kelvin H.',
    inPrimary: true,
    description: 'Community Outreach Director',
    imageFileName: null,
    website: 'https://www.kelvinbarrios.com/',
  },
  {
    year: '2020',
    candidateId: 'c5a6e91c-8c1e-7acc-21f1-98ad6a36280c|2020',
    optionalName: 'Bedwell, Sam',
    inPrimary: true,
    description: 'Small Business Entrepreneur',
    imageFileName: null,
    website: 'https://www.sambedwell.com/',
  },
  {
    year: '2020',
    candidateId: '8f7705a5-edf9-4c9d-879c-64de6455cf6c|2020',
    optionalName: 'Elo, Sean',
    inPrimary: true,
    description: 'Board Trustee, San Diego Community College District',
    imageFileName: 'sean_elo_8355.png',
    website: 'https://seanelo.com/',
  },
  {
    year: '2020',
    candidateId: 'c953b101-ff36-c494-f806-63f4b75bcabd|2020',
    optionalName: 'Gade, Andrew',
    inPrimary: true,
    description: 'Small Business Owner',
    imageFileName: null,
    website: 'https://andrewgade.com/',
  },
  {
    year: '2020',
    candidateId: '3d1760d4-3fcf-e717-521a-6fc0b1a1433b|2020',
    optionalName: 'Lee Dang, Johnny',
    inPrimary: true,
    description: 'Scientist',
    imageFileName: null,
    website: 'https://www.johnnylee2020.com/',
  },
  {
    year: '2020',
    candidateId: 'e279291e-0a3f-a4b1-6b3e-b53633440adb|2020',
    optionalName: 'Naismith, Ross',
    inPrimary: true,
    description: 'Music Teacher/Non-Profit Executive',
    imageFileName: null,
    website: 'https://vote4ross.com/',
  },
  {
    year: '2020',
    candidateId: null,
    optionalName: 'Soto, Alex',
    inPrimary: true,
    description: 'Unmanned Maritime Systems Manager',
    imageFileName: null,
    website: 'https://www.alexsoto2020.com/',
  },
  {
    year: '2018',
    candidateId: 'f6c70a3e-f869-9161-9dfb-a25242bc7b60|2018',
    optionalName: 'Beane, Jordan',
    inPrimary: true,
    description: 'Small Business Owner',
    imageFileName: null,
    website: 'www.jordanbeane.com',
  },
  {
    year: '2018',
    candidateId: 'd3d1c6e7-0add-49f1-9b3d-e9289e7efcf6|2018',
    optionalName: 'Campbell, Jennifer',
    inPrimary: true,
    description: 'Medical Doctor/Professor',
    imageFileName: null,
    website: 'www.drjen2018.com',
  },
  {
    year: '2018',
    candidateId: '',
    optionalName: 'Hahn, Randy',
    inPrimary: true,
    description: 'Publisher/Journalist/Sales Manager',
    imageFileName: null,
    website: 'randyhahn.com',
  },
  {
    year: '2018',
    candidateId: '',
    optionalName: 'Melton, Kevin',
    inPrimary: true,
    description: 'Retired Businessman',
    imageFileName: null,
    website: 'www.kevinmelton.net',
  },
  // From Voter Pamphlet below
  {
    year: '2018',
    candidateId: 'ac0632e7-4c9c-a2ea-a2ad-91a2f0ea736a|2018',
    optionalName: 'Pease, Bryan',
    inPrimary: true,
    description: 'Attorney',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: '8c775c40-41b1-670d-029d-4ccd370d7aec|2018',
    optionalName: 'Smiechowski, Danny',
    inPrimary: true,
    description: 'Real Estate Agent/Landlord',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: 'de716602-9097-7b64-0b50-09eeb5b8bb29|2018',
    optionalName: 'Zapf, Lorie',
    inPrimary: true,
    description: 'San Diego City Councilmember',
    imageFileName: null,
    website: 'www.LorieZapf.com',
  },
  {
    year: '2018',
    candidateId: 'd6ae4-161a-f4c1-bb8f-94986c8c6d47|2018',
    optionalName: 'Arthur, Neal',
    inPrimary: true,
    description: '',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: 'e4d5c830-0198-30a7-a5f8-a3053aed8df6|2018',
    optionalName: 'Cole, Myrtle',
    inPrimary: true,
    description: 'City Councilmember',
    imageFileName: null,
    website: 'www.myrtlecole.com',
  },
  {
    year: '2018',
    candidateId: '82cae978-49df-4a77-8793-0efffb7772b5|2018',
    optionalName: 'Montgomery, Monica',
    inPrimary: true,
    description: 'Attorney/Civil Rights Advocate',
    imageFileName: null,
    website: 'www.voteformonica.org',
  },
  {
    year: '2018',
    candidateId: '',
    optionalName: 'Villafranca, Tony',
    inPrimary: true,
    description: 'Pro-Life Advocate/Local Businessman',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: '',
    optionalName: 'Blattler, Jeremiah',
    inPrimary: true,
    description: 'Business Owner',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: '5687636e-2833-4df9-81a7-bcfa558d3f8e|2018',
    optionalName: 'Cate, Chris',
    inPrimary: true,
    description: '',
    imageFileName: null,
    website: 'www.chrisjcate.com',
  },
  {
    year: '2018',
    candidateId: '21c466c0-1f09-21ab-474f-d598c382da98|2018',
    optionalName: 'Egger, Kevin',
    inPrimary: true,
    description: '',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: 'ea70d40e-2106-2ed2-e82c-bd320c909e9c|2018',
    optionalName: 'Hough, Tommy',
    inPrimary: true,
    description: 'Broadcaster and Environmental Advocate',
    imageFileName: null,
    website: 'www.votetommy2018.com',
  },
  {
    year: '2018',
    candidateId: 'fa89f348-6e50-c8e6-6191-3253e929ef63|2018',
    optionalName: 'Nawabi, Fayaz', // Ahmad Fayaz Nawabi
    inPrimary: true,
    description: '',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: 'b5abecea-f161-5483-33ae-85d6b8559156|2018',
    optionalName: 'Valenti, Matt',
    inPrimary: true,
    description: 'Father / Attorney / Business Executive',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: '21367fcf-900d-004c-7349-b9d801973d63|2018',
    optionalName: 'Lazarus, Zachary',
    inPrimary: true,
    description: 'Entrepreneur / Small Business Owner',
    imageFileName: null,
    website: '',
  },
  {
    year: '2018',
    candidateId: '47f2d909-5f52-d85c-b465-3ad7714b1da5|2018',
    optionalName: 'Martinez, Antonio',
    inPrimary: true,
    description: 'School Boardmember/Community Healthcare Counselor',
    imageFileName: null,
    website: 'www.AntonioMartinezSD.com',
  },
  {
    year: '2018',
    candidateId: '4adb5c04-3d8d-4fdd-9cd4-1227cbde766e|2018',
    optionalName: 'Moreno, Vivian',
    inPrimary: true,
    description: 'Council Representative',
    imageFileName: null,
    website: 'www.vivianmorenosd.com',
  },
  {
    year: '2018',
    candidateId: 'befcf0c9-a490-101a-d18c-b39839f254f2|2018',
    optionalName: 'Ramírez, Christian',
    inPrimary: true,
    description: 'Community Advocate',
    imageFileName: null,
    website: '',
  },

  // From 2016 Voter Pamphlet below
  {
    year: '2016',
    candidateId: '316b8e67-85de-0d7d-15b6-968f31d18fbb|2016',
    optionalName: 'Faulconer, Kevin',
    inPrimary: true,
    description: 'Mayor',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '1f8b6d29-1048-3276-4222-609c05db5f92|2016',
    optionalName: 'Harris, Ed',
    inPrimary: true,
    description: 'San Diego Lifeguard Sergeant',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: 'b3743dcf-ba16-1389-aa07-d28f26d4a94d|2016',
    optionalName: 'Saldaña, Lori',
    inPrimary: true,
    description: 'Community College Technology Teacher',
    imageFileName: null,
    website: '',
  },

  {
    year: '2016',
    candidateId: 'ba651599-423e-0cf1-f157-b0a4b88bb39a|2016',
    optionalName: 'Cabrera, Gil',
    inPrimary: true,
    description: 'Attorney/Small Business Owner',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '84c9a5f7-ebae-a56c-9889-43915ca5fb92|2016',
    optionalName: 'Castellanos, Rafael',
    inPrimary: true,
    description: 'Attorney/Port Commissioner',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: 'f7957bf1-8701-4456-93dc-6c7022c86b6d|2016',
    optionalName: 'Elliott, Mara',
    inPrimary: true,
    description: 'Chief Deputy City Attorney',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '2944c707-5507-ee79-23f4-dc72ff5cf8e1|2016',
    optionalName: 'Hickey, Robert',
    inPrimary: true,
    description: 'Deputy District Attorney',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: 'ac0632e7-4c9c-a2ea-a2ad-91a2f0ea736a|2016',
    optionalName: 'Pease, Bryan',
    inPrimary: true,
    description: 'Consumer Attorney',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: 'be0a57fb-c0f0-bbd5-0d42-44a6560cbd21|2016',
    optionalName: 'Bry, Barbara',
    inPrimary: true,
    description: 'High-tech Entrepreneur',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: 'e8b85437-f58a-42b4-e31e-176d55f0a66d|2016',
    optionalName: 'Ellis, Ray', // Raymond Gibbons Ellis
    inPrimary: true,
    description: 'Community Volunteer',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '',
    optionalName: 'Heiskala, Kyle',
    inPrimary: true,
    description: 'City Council Representative',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '02245c51-b748-e56a-e20c-80c49246fabb|2016',
    optionalName: 'Lightner, Bruce',
    inPrimary: true,
    description: 'Engineer/Inventor/Business Owner',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '',
    optionalName: 'Rodolico, Louis',
    inPrimary: true,
    description: '',
    imageFileName: null,
    website: '',
  },

  {
    year: '2016',
    candidateId: 'bcf9f527-4eec-598e-f65c-1eaf37efbe76|2016',
    optionalName: 'Bernal, Anthony',
    inPrimary: true,
    description: 'City Council Representative',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: 'be2c4905-087b-6971-914c-c70be0580f07|2016',
    optionalName: 'Sanborn, Scott',
    inPrimary: true,
    description: 'Special Forces Weapons Sergeant',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '841e9204-e2a0-1849-c1af-97bbea39db09|2016',
    optionalName: 'Ward, Chris',
    inPrimary: true,
    description: 'Senate Chief of Staff',
    imageFileName: null,
    website: '',
  },

  {
    year: '2016',
    candidateId: '537d4c20-4534-eada-3c1f-9bf6459ce2bd|2016',
    optionalName: 'Kersey, Mark',
    inPrimary: true,
    description: 'Councilman / Small Business Owner',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '633e1d76-92c1-a03c-ef7a-57d475d65617|2016',
    optionalName: 'Mikas, Keith',
    inPrimary: true,
    description: '',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '',
    optionalName: 'Tsimboukakis, Frank',
    inPrimary: true,
    description: 'Investment Manager / Businessman',
    imageFileName: null,
    website: '',
  },

  {
    year: '2016',
    candidateId: '34870289-0812-8e99-4c7a-1be1b67106dc|2016',
    optionalName: 'Caballero, Jose',
    inPrimary: true,
    description: 'Small Business Owner',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '2490aa6b-ef13-2850-e47f-e3a23d936ffa|2016',
    optionalName: 'Decesare, Justin',
    inPrimary: true,
    description: 'Businessman / Entrepreneur',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: 'f311f300-4421-5320-a6b7-a2641a33c6ce|2016',
    optionalName: 'Sherman, Scott',
    inPrimary: true,
    description: 'Small Business Owner / Councilmember',
    imageFileName: null,
    website: '',
  },

  {
    year: '2016',
    candidateId: '22b107b9-41c1-0a2d-c73f-c5629acf5e00|2016',
    optionalName: 'Flores, Ricardo',
    inPrimary: true,
    description: 'Chief of Staff',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '',
    optionalName: 'Gomez, Georgette',
    inPrimary: true,
    description: 'Nonprofit Executive / Health Advocate',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: 'a3137711-dfe5-bcd7-0005-d247cda5a627|2016',
    optionalName: 'Martinez, Araceli',
    inPrimary: true,
    description: 'Attorney at Law',
    imageFileName: null,
    website: '',
  },
  {
    year: '2016',
    candidateId: '32782476-0d77-432e-b12e-0ce25ab027f6|2016',
    optionalName: 'Saez, Sarah',
    inPrimary: true,
    description: 'Policy and Program Director',
    imageFileName: null,
    website: '',
  },
];
